### ISSUE TITLE
Compare widgets with deform

### ISSUE THREAD

**Issue by uralbash** [ergo/ziggurat_form_demo#4]
Deform has various widgets that require js, for example:
- [deform.widget.MoneyInputWidget](http://deformdemo.repoze.org/money_input/)
- [deform.widget.AutocompleteInputWidget](http://deformdemo.repoze.org/autocomplete_input/)
- etc...

As I understand zigg_form doesn't provide any js with widget. We must think of how to make custom widgets using js.

Variants:
- You can add a single file like `deform.js`, but it is very clumsy method.
- Add meta information in the widget (like `{"js": ["/static/money.js", "test.js"]}`) and load it dynamicly in template.
-

**Comment by ergo** [comment]
Yeah, I don't want to provide anything that is JS dependant, this will be up to the users to implement using their framework, however someone can do zigg_form.ext.foowidgets - that will implement this.
